### ISSUE TITLE
new rule: ensure IAM policies are attached only to groups or roles

### ISSUE THREAD

**Issue by blakefrantz** [awslabs/aws-config-rules#10]
See item 1.15 in https://benchmarks.cisecurity.org/tools2/amazon/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.0.0.pdf

**Comment by jongogogo** [comment]
Pushed as Managed Rule https://docs.aws.amazon.com/config/latest/developerguide/iam-user-no-policies-check.html
