### ISSUE TITLE
IAM_USER_MFA_ENABLED error 

### ISSUE THREAD

**Issue by mbotmcc** [awslabs/aws-config-rules#101]
getting an error when running the lambda function

> An error occurred (ValidationException) when calling the PutEvaluations operation: 1 validation error detected: Value ' ... 'evaluations' failed to satisfy constraint: Member must have length less than or equal to 100: ValidationException
Traceback (most recent call last):
File "/var/task/IAM_USER_MFA_ENABLED.py", line 428, in lambda_handler
AWS_CONFIG_CLIENT.put_evaluations(Evaluations=evaluations, ResultToken=resultToken, TestMode=testMode)
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 612, in _make_api_call
raise error_class(parsed_response, operation_name)

any ideas?

**Comment by jongogogo** [comment]
Hey, do you have more than 100 IAM users?

**Comment by mbotmcc** [comment]
yeah just realised we got almost 200 users

**Comment by jongogogo** [comment]
Hey @mbotmcc , this should solve the challenge. Please let me know if it works for you.
Jon

**Comment by jongogogo** [comment]
This is a timing consideration, brand new user might not be fully recorded. After a while it will appear normally. I clean-up the annotation and added the username, but it might not help if the username is not recorded yet.
Try again to re-evaluate, please. Works?

**Comment by mbotmcc** [comment]
that works, thanks!

**Comment by jongogogo** [comment]
Awesome, feel free to raise anytime
