### ISSUE TITLE
Rule for Open Ingress Security Groups

### ISSUE THREAD

**Issue by JonLittleIT** [awslabs/aws-config-rules#102]
Please make a rule we can use to monitor for users that use wide open 0.0.0.0. 

It only checks for certain ports not wide open groups.

**Comment by jongogogo** [comment]
We have that in the pipe, stay tuned :)

**Comment by jongogogo** [comment]
Posted, check the rule: https://github.com/awslabs/aws-config-rules/tree/master/python/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS

**Comment by JonLittleIT** [comment]
I used this and it works.

thank you guys for getting this out fast!

currently testing out with phantom and Splunk.

**Comment by jongogogo** [comment]
Awesome! 
If you got other needs of rules, glad to consider.
