### ISSUE TITLE
RDS_NOT_PUBLIC object is not subscriptable error

### ISSUE THREAD

**Issue by mbotmcc** [awslabs/aws-config-rules#109]
The lambda errors with the following

> 'NoneType' object is not subscriptable: TypeError
Traceback (most recent call last):
File "/var/task/RDS_NOT_PUBLIC.py", line 315, in lambda_handler
compliance_result = evaluate_compliance(event, configuration_item, valid_rule_parameters)
File "/var/task/RDS_NOT_PUBLIC.py", line 80, in evaluate_compliance
is_publicly_accessible = configuration_item["configuration"]["publiclyAccessible"]
TypeError: 'NoneType' object is not subscriptable

any ideas?

**Comment by jongogogo** [comment]
Hey, have you deploy the rule with configuration change on "AWS::RDS::DBInstance"? This error is usually due at a periodic trigger (the rule is not designed for that).

**Comment by mbotmcc** [comment]
sorry my bad. That was it. Thanks!

**Comment by jongogogo** [comment]
Cool! 

An advice @mbotmcc : Consider using the RDK to deploy rule: https://github.com/awslabs/aws-config-rdk

The rules in a folder in this repo are compatible.
0 - Have AWS CLI and a default profile set up
1 - Copy the RDS_NOT_PUBLIC folder in your working folder
2 - 
```
pip install rdk
rdk deploy RDS_NOT_PUBLIC
```
3 - Enjoy
