### ISSUE TITLE
new rule: ensure the S3 bucket CloudTrail logs to is not publicly accessible

### ISSUE THREAD

**Issue by blakefrantz** [awslabs/aws-config-rules#11]
See 2.3 from https://benchmarks.cisecurity.org/tools2/amazon/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.0.0.pdf

**Comment by jongogogo** [comment]
https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-public-read-prohibited.html
