### ISSUE TITLE
new rule: ensure CloudTrail trails are integrated with CloudWatch Logs 

### ISSUE THREAD

**Issue by blakefrantz** [awslabs/aws-config-rules#12]
See 2.4 from https://benchmarks.cisecurity.org/tools2/amazon/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.0.0.pdf

**Comment by ryflood** [comment]
It is currently possible to check that there is at least one CloudTrail Trail with a particular desired configuration with the CLOUD_TRAIL_ENABLED managed rule. You can include the `cloudWatchLogsLogGroupArn` parameter in the InputParameters to check that CloudTrail logging to CloudWatch Logs is enabled. [More details](http://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_use-managed-rules.html#d0e3962).

Does this cover your use case?

**Comment by jongogogo** [comment]
No reply, closing.
