### ISSUE TITLE
aws config custom rule not found

### ISSUE THREAD

**Issue by sandygvs** [awslabs/aws-config-rules#121]
Hello Folks,

Am trying to set aws config custom rule for security group with reference to this blog https://aws.amazon.com/blogs/security/how-to-monitor-aws-account-configuration-changes-and-api-calls-to-amazon-ec2-security-groups/. Here am trying with method 1 and it is mentioned at step 4 (Create the Python Lambda function using the code from the AWS Config rules library on GitHub). when i checked the code at the source (https://github.com/awslabs/aws-config-rules/blob/master/python/ec2_security_group_ingress.py) returns 404 page not found. Would be great if i get the code for testing. 

Much appreciate your help on this!!!

**Comment by jongogogo** [comment]
You can use https://github.com/awslabs/aws-config-rules/blob/master/python/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS.py which should achieve the same outcome.
Please let me know if it doesnt.

**Comment by sandygvs** [comment]
Thanks for the script, let me check and update you...

**Comment by sandygvs** [comment]
@jongogogo Could you please help here

**Comment by jongogogo** [comment]
Hi @sandygvs, didn't see your update, my bad.
1 - In the rule definition, you can change the scope of changes and use tags. The rule should work, no worries (See step 5 in the method 1: https://aws.amazon.com/blogs/security/how-to-monitor-aws-account-configuration-changes-and-api-calls-to-amazon-ec2-security-groups/)
2 - For revocation, the best practice is to use CloudWatch Events on Config events, then trigger a lambda that does what you want (see https://docs.aws.amazon.com/config/latest/developerguide/monitor-config-with-cloudwatchevents.html). Some revocation code is available there (in node though): https://github.com/cloudconformity/auto-remediate/tree/master/functions

**Comment by sandygvs** [comment]
Thanks for your update, let me test it and update you :)
