### ISSUE TITLE
new rule: ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket

### ISSUE THREAD

**Issue by blakefrantz** [awslabs/aws-config-rules#13]
See 2.6 from https://benchmarks.cisecurity.org/tools2/amazon/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.0.0.pdf

**Comment by jongogogo** [comment]
Pushed as managed rule: https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-logging-enabled.html
