### ISSUE TITLE
[Feedback requested] New rule on Redshift Cluster to check public accessibility.

### ISSUE THREAD

**Issue by shikharj05** [awslabs/aws-config-rules#133]
New rule to verify that the Redshift cluster is not publicly accessible.

Please provide comments on the gherkin if any.

---

**Description**:
  Check whether the Amazon Redshift clusters are not publicly accessible. The rule is NON_COMPLIANT if the publiclyAccessible field is true in the cluster configuration item. 

**Trigger**:
  Configuration Change on AWS::Redshift::Cluster

**Reports on:**
  AWS::Redshift::Cluster
```
Rule Parameters:
  None

Scenarios:
  Scenario: 1
     Given: The publiclyAccessible field is true in the cluster configuration item. 
     Then: Return NON_COMPLIANT
  Scenario: 2
     Given: The publiclyAccessible field is false in the cluster configuration item. 
     Then: Return COMPLIANT
```

**Comment by jongogogo** [comment]
Merged
