### ISSUE TITLE
new rule: ensure no security groups allow ingress from 0.0.0.0/0 to port 22

### ISSUE THREAD

**Issue by blakefrantz** [awslabs/aws-config-rules#14]
See 4.1 from https://benchmarks.cisecurity.org/tools2/amazon/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.0.0.pdf

**Comment by aaronkhoo** [comment]
This functionality is already provided by the Managed Rule restricted-common-ports, as well as sample code in https://github.com/awslabs/aws-config-rules/blob/master/python/ec2-exposed-instance.py for users that require more flexibility. Is there something beyond these two rules that you were looking for?

**Comment by msambol** [comment]
A few options:

1/ INCOMING_SSH_DISABLED
2/ https://github.com/awslabs/aws-config-rules/blob/master/python/ec2-exposed-group.py

**Comment by konkarabhijeet** [comment]
Uploading this code in lambda function while testing we are facing invoking issue. which parameter we should pass for invoking this code?
