### ISSUE TITLE
New Rule: Ensure that a list of specific KMS keys are not being scheduled for deletion

### ISSUE THREAD

**Issue by 0xjjoyy** [awslabs/aws-config-rules#147]
Use case is a detective control to ensure that a whitelist of KMS keys are not being scheduled for deletion.

**Comment by jongogogo** [comment]
Cool!

**Comment by 5u5hma** [comment]
"""
#####################################
##           Gherkin               ##
#####################################

Rule Name:
    KMS_KEYS_TO_NOT_DELETE

Description:
    Check if the given KMS keys are not scheduled for deletion. The rule is NON_COMPLAINT if the KMS Keys are scheduled for deletion.

Trigger:
    Periodic

Reports on:
    AWS::KMS::Key

Rule Parameters:
    kmsKeyids (Required)
    Comma-separated list of kmsKeyids, that are expected not to be scheduled for deletion.

Scenarios:

    Scenario 1:
    Given: Rule parameter kmsKeyids provided
      And: Not Valid one
     Then: Return ERROR

    Scenario 2:
    Given: No KMS Keys in Account
     Then: Return NOT_APPLICABLE

    Scenario 3:
    Given: At least 1 KMS key is present in the AWS Account
      And: Valid rule parameter kmsKeyids provided
      And: The KMS Key is not the one in parameter 
      And: The KMS Key is not scheduled for deletion
     Then: Return NOT_APPLICABLE

    Scenario 4:
    Given: At least 1 KMS key is present in the AWS Account
      And: Valid rule parameter kmsKeyids provided
      And: The KMS Key is not the one in parameter 
      And: The KMS Key is scheduled for deletion
     Then: Return NOT_APPLICABLE

    Scenario 5:
    Given: At least 1 KMS key is present in the AWS Account
      And: Valid rule parameter kmsKeyids provided
      And: The KMS Key in the parameter is scheduled for deletion
     Then: Return NON_COMPLAINT

    Scenario 6:
    Given: At least 1 KMS key is present in the AWS Account
      And: Valid rule parameter kmsKeyids provided
      And: The KMS Key in the parameter is not scheduled for deletion
     Then: Return COMPLAINT

"""

**Comment by 5u5hma** [comment]
Please review the Gherkin and let me know for changes.

**Comment by 0xjjoyy** [comment]
Thank you. If there are No KMS keys in the account and this particular Config rule is enabled and kmsKeyids are specified, should there be an ERROR, rather than non compliant? Would this  be incorrectly configured, similar to Scenario 1?

```

Scenario 2:
Given: No KMS Keys in Account
 Then: Return NOT_APPLICABLE
```

**Comment by 5u5hma** [comment]
So the scenario 2 does not declare it as NON_COMPLAINT it declares it as NOT_APPLICABLE. This would basically intimidate the customer when he runs this rule as "No resources in scope". By this customer will understand that there no KMS Keys in his accounts and hence there was nothing to be evaluated. Also, if there no KMS Keys in account I dont think so customer will be able to provide any kind of KMSKeysids as the input. Also, throwing error might confuse the customer that when I dont have resources then why is it even trying to evaluate and throwing error. Should it not just that there no resources which it can evaluate.

Hope this provides some clarity let me know any further questions.

**Comment by jongogogo** [comment]
In the current logic, the scenario 2 and the fact that the parameter is mandatory are not compatible.

I suggest another way:
- Make the parameter optional
- If there is no parameter, check that all the (customer managed) CMK are not scheduled for deletion.
- If there is a parameter, check only those specific keys.

Other comments
- Please add in the description. 'The rule is not applicable to CMKs that have imported key material and AWS-managed CMKs. '

**Comment by 5u5hma** [comment]
Ok Sure. I will incorporate them and post the update gherkin for review by EOD.

**Comment by 5u5hma** [comment]
"""
#####################################
##           Gherkin               ##
#####################################

Rule Name:
    KMS_KEYS_TO_NOT_DELETE

Description:
    Check if the Customer Managed keys are not scheduled for deletion. The rule is NON_COMPLAINT if the Customer Managed Keys are scheduled for deletion. This rule does not include AWS managed and Imported Keys.

Trigger:
    Periodic

Reports on:
    AWS::KMS::Key

Rule Parameters:
    kmsKeyids (Optional)
    Comma-separated list of Customer Managed KeyIds, that are expected not to be scheduled for deletion.

Scenarios:

    Scenario 1:
    Given: Rule parameter kmsKeyids not provided or not valid
     Then: Return ERROR

    Scenario 2:
    Given: No CMKs in Account
     Then: Return NOT_APPLICABLE

    Scenario 3:
    Given: At least 1 CMK is present in the AWS Account
      And: Rule parameter kmsKeyids are not configured
      And: The KMS Key is not scheduled for deletion
     Then: Return COMPLAINT

    Scenario 4:
    Given: At least 1 CMK is present in the AWS Account
      And: Rule parameter kmsKeyids are configured and valid
      And: The KMS Key is not the one in parameter 
      And: The KMS Key is not scheduled for deletion
     Then: Return COMPLAINT

    Scenario 5:
    Given: At least 1 CMK is present in the AWS Account
      And: Rule parameter kmsKeyids are configured and valid
      And: The KMS Key is not the one in parameter 
      And: The KMS Key is scheduled for deletion
     Then: Return COMPLAINT

    Scenario 6:
    Given: At least 1 KMS key is present in the AWS Account
      And: Rule parameter kmsKeyids are configured and valid
      And: The KMS Key in the parameter is not scheduled for deletion
     Then: Return COMPLAINT

    Scenario 7:
    Given: At least 1 KMS key is present in the AWS Account
      And: Rule parameter kmsKeyids are not configured
      And: The KMS Key in the account is scheduled for deletion
     Then: Return NON_COMPLAINT   

    Scenario 8:
    Given: At least 1 KMS key is present in the AWS Account
      And: Rule parameter kmsKeyids are configured and valid
      And: The KMS Key in the parameter is scheduled for deletion
     Then: Return NON_COMPLAINT

"""

**Comment by 5u5hma** [comment]
Please find the updated gherkin. Let me know if any changes.

**Comment by jongogogo** [comment]
Changed the gherkin, please review. Some typo (like COMPLAINT to COMPLIANT)
