### ISSUE TITLE
new rule: ensure no security groups allow ingress from 0.0.0.0/0 to port 3389

### ISSUE THREAD

**Issue by blakefrantz** [awslabs/aws-config-rules#15]
See 4.2 from https://benchmarks.cisecurity.org/tools2/amazon/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.0.0.pdf

**Comment by ryflood** [comment]
related to https://github.com/awslabs/aws-config-rules/issues/14

**Comment by aaronkhoo** [comment]
This functionality is already provided by the Managed Rule restricted-common-ports, as well as sample code in https://github.com/awslabs/aws-config-rules/blob/master/python/ec2-exposed-instance.py for users that require more flexibility. Is there something beyond these two rules that you were looking for?

**Comment by ryflood** [comment]
I believe you want to specify the ports you want to restrict in the InputParameters of the PutConfigRule request: https://docs.aws.amazon.com/config/latest/APIReference/API_ConfigRule.html#config-Type-ConfigRule-InputParameters

**Comment by jongogogo** [comment]
Existing managed rules: https://docs.aws.amazon.com/config/latest/developerguide/restricted-common-ports.html
