### ISSUE TITLE
New rule on Enterprise support plan enabled

### ISSUE THREAD

**Issue by santosh07bec** [awslabs/aws-config-rules#151]
```python
'''
Rule Name:
  ENTERPRISE_SUPPORT_PLAN_ENABLED

Description:
  Check whether the Enterprise Support Plan is enabled for an AWS Account.

Trigger:
  Periodic

Reports on:
  AWS::::Account

Rule Parameters:
  None

Scenarios:
  Scenario: 1
     Given: AWS Support API call errors out with SubscriptionRequired exception while using the DescribeSeverityLevels API call
      Then: Return NON_COMPLIANT with Annotation "The AWS Enterprise Support Plan is not enabled for this AWS Account."
  Scenario: 2
     Given: The AWS Account does not have access to "critical" case severity level as returned by the AWS Support API DescribeSeverityLevels
      Then: Return NON_COMPLIANT with Annotation "The AWS Enterprise Support Plan is not enabled for this AWS Account."
  Scenario: 3
     Given: The AWS Account has access to "critical" case severity level as returned by the AWS Support API DescribeSeverityLevels
      Then: Return COMPLIANT
'''
```

**Comment by jongogogo** [comment]
Can you please add the API you are calling in the Scenario 1 and 2 at the end of the "Given" statement?
In scenario 1, return COMPLIANT.
The scenario 2, change the annotation "The AWS Enterprise Support Plan is not enabled for this AWS Account."

**Comment by santosh07bec** [comment]
Gherkin has been updated as per above suggestion.

**Comment by jongogogo** [comment]
Look good for me, thanks!

API link for reference: https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeSeverityLevels.html

**Comment by shikharj05** [comment]
@santosh07bec If an account is not subscribed to Business or Enterprise Support it cannot use Support API. Reference: https://aws.amazon.com/premiumsupport/plans/

**Comment by santosh07bec** [comment]
Modified the Gherkin as per shikharj05 suggestion.
@ jongogogo, could  you please take a look again on this gherkin and provide your comments?

**Comment by jongogogo** [comment]
Ok good to go!
