### ISSUE TITLE
new rule: ensure the default security group restricts all traffic

### ISSUE THREAD

**Issue by blakefrantz** [awslabs/aws-config-rules#16]
See 4.4 from https://benchmarks.cisecurity.org/tools2/amazon/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.0.0.pdf

**Comment by jongogogo** [comment]
Just pushed: https://github.com/awslabs/aws-config-rules/tree/master/python/VPC_DEFAULT_SECURITY_GROUP_BLOCKED
