### ISSUE TITLE
Desired instance type rule

### ISSUE THREAD

**Issue by jicowan** [awslabs/aws-config-rules#19]
The desired instance type rule does not seem to work using desiredInstanceType as a parameter because after it's through evaluating it says, "no results are available."  I'm not using t2.smalls in my environment so I would expect there to be multiple violations.  I tried changing instance types because I figured that would trigger the rule, but the results didn't change.  When I looked at the monitoring tab for the lambda function, it didn't appear that the function was invoked even though I specified in the ARN of the function in the rule.

**Comment by ryflood** [comment]
This was confirmed as a transient issue with the AWS Lambda service (reported at http://status.aws.amazon.com/). If you are still experiencing issues, please feel free to reopen.
