### ISSUE TITLE
New rule on ELB_DELETION_PROTECTION_ENABLED

### ISSUE THREAD

**Issue by kritijha** [awslabs/aws-config-rules#243]
New rule to verify that the ELB, both ALB and NLB, have termination protection enabled.

Please provide comments on the gherkin if any.

---
```
Description:
  Check whether an Elastic Load Balancer has termination protection enabled.

Trigger:
  Configuration Changes

Reports on:
  AWS::ElasticLoadBalancingV2::LoadBalancer

Scenarios:
  Scenario: 1
     Given: deletion_protection.enabled in is set to False in 'LoadBalancerAttributes' in the configuration item
      Then: Return NON_COMPLIANT with annotation "This Elastic Load Balancer does not have termination protection enabled."
  Scenario: 2
     Given: deletion_protection.enabled is set to True in 'LoadBalancerAttributes' in the configuration item
      Then: Return COMPLIANT

**Comment by jongogogo** [comment]
It can be Configuration Change. I found that the info are logging in the "supplementaryConfiguration" section of the CI.

**Comment by kritijha** [comment]
Ohhh. Thanks @jongogogo 
Let me check. I'll modify it accordingly.

**Comment by kritijha** [comment]
@jongogogo modified it to config change.

**Comment by jongogogo** [comment]
- No need of scenario 1, since it is Configuration Change
- You have a double space in `Configuration  Changes`

**Comment by kritijha** [comment]
@jongogogo Made the change.

**Comment by jongogogo** [comment]
Good to go (bit late) :)
