### ISSUE TITLE
New Rule on Amazon S3 to ensure object logging is enabled

### ISSUE THREAD

**Issue by 0xjjoyy** [awslabs/aws-config-rules#245]
For specified list of Amazon S3 buckets, object logging should be enabled. If object logging is not enabled, raise noncompliance with details of the misconfigured object logging.

**Comment by jongogogo** [comment]
We are working on this rule, I believe. Just calling differently: is it what you are looking for.

https://github.com/awslabs/aws-config-rules/issues/195
https://github.com/awslabs/aws-config-rules/pull/220

**Comment by 0xjjoyy** [comment]
Yes, that appears to be the [object-level logging for an S3 Bucket with AWS CloudTrail Data Events](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/enable-cloudtrail-events.html).
