### ISSUE TITLE
Update CLOUD_TRAIL_ENABLED to designate specific trail name

### ISSUE THREAD

**Issue by ryanpodonnell1** [awslabs/aws-config-rules#281]
Currently there are only s3BucketName, snsTopicArn, cloudWatchLogsLogGroupArn parameters:
![image](https://user-images.githubusercontent.com/48141361/62976506-c1077880-bdea-11e9-80c2-2910fc90a6ad.png)

Adding a new parameter for trailName to specify which specific trail to look for. Our organization has multiple trails and we only care about the one that feeds our own Security Account.

**Comment by jongogogo** [comment]
If the objective is to deliver the CloudTrail logs into the Security Account, then specifying the bucket you are using in the Security Account (via the s3BucketName) provides more assurance than the name of the trail. Am I missing something?

**Comment by ryanpodonnell1** [comment]
Ah so the bucketName parameter actually refers to the configured bucket in the trail config itself. I thought it meant it was looking for the destination trail bucket In the central account. If that’s the case we can close this.

**Comment by jongogogo** [comment]
Great, feel free to have a try and reopen if anything.
