### ISSUE TITLE
boto3.client.describe_config_rules returns rule is ACTIVE when it is EVALUATING

### ISSUE THREAD

**Issue by elishaROBINSON** [awslabs/aws-config-rules#284]
I created a config rule using the boto3 client with python 2.7 and the rule returns ACTIVE when it is actually evaluating . The result being that i get no NON_COMPLIANT resources when it is actually expected. maintaing a sleep() for x seconds does not seem sustainable. are there any other ways to get the correct evaluation state of the rule.

**Comment by jongogogo** [comment]
We can look into it. Please parse your code. By the way, are you using the Rule Development Kit (https://github.com/awslabs/aws-config-rdk) ?

**Comment by elishaROBINSON** [comment]
nope just vanila boto3(1.9) . anyway i figured it out i am using the function describe_config_rule_evaluation_status to get the current evaluation status of the config rule now . i think i should probably raise this as an issue with the boto3 team , at the very least this is improper documentation.
