### ISSUE TITLE
S3_BUCKET_PUBLIC_READ_PROHIBITED rule cannot be isolated to a specific s3 resource

### ISSUE THREAD

**Issue by crispyblock** [awslabs/aws-config-rules#297]
On the AWS config rule console, specifying the _Resource identifier_ does not limit the scope of this config rule to the designated resource.
Am I misunderstanding the intent of this field?

I set the 
Resources: **S3:Bucket**  
Resource Identifier: [**bucket ARN**] or [**bucket name**]   (I have tried both)

The rule still evaluates all s3 buckets in my account;

Please let me know if I am misunderstanding the intended use of this field.

**Comment by jongogogo** [comment]
Hi, I just gave it a try. I observed the same unintended behavior. Let me raise it to the team.

**Comment by jongogogo** [comment]
Got a heads up, it has been fixed. Please reopen an issue if anything. Thanks!
