### ISSUE TITLE
ELB_ALB_PREDEFINED_SSL_CHECK - failed to satisfy constraint

### ISSUE THREAD

**Issue by kingchad5** [awslabs/aws-config-rules#304]
I am running into an issue with this lambda.  It appears I am running into an issue where I have more than 100 ELB/ALBs in my account (101 to be exact).  Here is the cloudwatch log

>'evaluations' failed to satisfy constraint: Member must have length less than or equal to 100
Traceback (most recent call last):
  File "/var/task/ELB_ALB_PREDEFINED_SSL_CHECK.py", line 437, in lambda_handler
    AWS_CONFIG_CLIENT.put_evaluations(Evaluations=evaluations, ResultToken=resultToken, TestMode=testMode)

I confirmed my setup runs in an account with less than 100 ELB/ALBs.  Is there a paging issue where it goes to get the next_token?  Any help would be appreciated.

**Comment by jongogogo** [comment]
Corrected the code to support more than 100 eval in #305

**Comment by kingchad5** [comment]
This resolved the issue, Thanks for the quick response!
