### ISSUE TITLE
Error: invokingEvent.s3ObjectKey is not defined

### ISSUE THREAD

**Issue by MichaelLiZhou** [awslabs/aws-config-rules#40]
I am assuming this will happen to any js that uses s3objectkey but specifically I run into the issue running iam_password_policy_enabled-periodic.js

I get this error from the Cloudtrail logs mentioning that the lambda function is not running correctly and that the error is because of 

Error: invokingEvent.s3ObjectKey is not defined

Is an s3ObjectKey suppose to be in the event?

**Comment by zealvora** [comment]
Yes, I get similar issue with other functions as well like Config Enabled Checker one which is JS.

**Comment by aaronkhoo** [comment]
AWS Config released a new way to implement periodic rules back in July 2016. See https://aws.amazon.com/about-aws/whats-new/2016/07/now-evaluate-aws-config-rules-on-demand-trigger-rules-on-changes-and-periodicity-and-more for details. This new approach no longer relies on configuration snapshots to be delivered to trigger a periodic rule. For an example of periodic rule that uses the new approach, see http://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_nodejs-sample.html#periodic-example-rule 

Also see "MessageType" under SourceDetail at http://docs.aws.amazon.com/config/latest/APIReference/API_SourceDetail.html. "ScheduledNotification" is the recommended approach for implementing periodic rules. "ConfigurationSnapshotDeliveryCompleted" is the legacy version that leverages configuration snapshots. If you create a periodic rule through the AWS Config console, it will be a ScheduledNotification rule. 

This is why the periodic rules that use the old configuration snapshot based approach have been moved under the "old-periodic" folder. See this commit for more details: https://github.com/awslabs/aws-config-rules/commit/ba42d340edd3a4cbd7b4fe0f447fcf4b084ee9bd

For an example of a hybrid (both periodic and change triggered) rule that uses the recommended ScheduledNotification approach, see https://github.com/awslabs/aws-config-rules/blob/master/python/ec2_require_ebs_snapshots_for_volumes

**Comment by ramkama** [comment]
@MichaelLiZhou @zealvora @aaronkhoo @aws-dash 

I am also facing same the issue while invoking these scripts even with the scripts under node. Did you find any solution to these?

**Comment by jongogogo** [comment]
Please reopen if still required
