### ISSUE TITLE
Parameters for python/ec2-exposed-group.py

### ISSUE THREAD

**Issue by wlkong** [awslabs/aws-config-rules#45]
20. Ensure that no security groups allow public access to the specified ports.
Description: Checks that all security groups block access to the specified ports.
python/ec2-exposed-group.py
Trigger Type: Change Triggered Scope of Changes: EC2:SecurityGroup Accepted Parameters: examplePort1, exampleRange1, examplePort2, ... Example Values: 8080, 1-1024, 2375, ...

Can some explain what Parameters need to be passed to this script? For example, to block Ports 20-21.

**Comment by jongogogo** [comment]
Hey, apologies for the late response. We pushed a new tule in the repo, which have all the doc in the main .py: https://github.com/awslabs/aws-config-rules/tree/master/python/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS
Feel free to reopen if anything
