### ISSUE TITLE
[Python] IAM Inactive User / Unused User

### ISSUE THREAD

**Issue by markusbecker** [awslabs/aws-config-rules#47]
Hey guys,

anyone having the same issue? The rules that check for inactive users (or users that have never logged in) is change triggered. So when somebody logs in, there is no change to the resource and it wont get evaluated again. So the user is still shown as inactive or unused. (Both rules act the same way)
When you change the trigger type to periodic there has to be some different code since you wont get the resource as input parameter, correct?

best regards,
Markus

**Comment by mooninite** [comment]
The code snippet here is for IAM user passwords. If you do not use passwords the code snippet will not work for you.

**Comment by jongogogo** [comment]
Hi folks, better late than never. we pushed a new rule, that do the job. Have a look: https://github.com/awslabs/aws-config-rules/tree/master/python/IAM_USER_USED_LAST_90_DAYS
Feel free to reopejn if anything.
