### ISSUE TITLE
MFA-enabled rule is wrongly evaluating cli users 

### ISSUE THREAD

**Issue by umerebryx** [awslabs/aws-config-rules#58]
Hi Guys,

One of your [rule](https://github.com/awslabs/aws-config-rules/blob/master/python/iam-mfa.py) that check if users have MFA enabled is wrongly evaluating cli users that don't have a valid login_profile hence can't have MFA. I have made some changes to the code which will make it only look for relevant users:
```

import json
import boto3


APPLICABLE_RESOURCES = ["AWS::IAM::User"]


def evaluate_compliance(configuration_item):
    if configuration_item["resourceType"] not in APPLICABLE_RESOURCES:
        return "NOT_APPLICABLE"

    user_name = configuration_item["configuration"]["userName"]

    iam = boto3.client("iam")
		try: 
        iam.get_login_profile(UserName=user_name)
    except:
        return "COMPLIANT"
    mfa = iam.list_mfa_devices(UserName=user_name)

    if len(mfa["MFADevices"]) > 0:
        return "COMPLIANT"
    else:
        return "NON_COMPLIANT"


def lambda_handler(event, context):
    invoking_event = json.loads(event["invokingEvent"])
    configuration_item = invoking_event["configurationItem"]
    result_token = "No token found."
    if "resultToken" in event:
        result_token = event["resultToken"]

    config = boto3.client("config")
    config.put_evaluations(
        Evaluations=[
            {
                "ComplianceResourceType":
                    configuration_item["resourceType"],
                "ComplianceResourceId":
                    configuration_item["resourceId"],
                "ComplianceType":
                    evaluate_compliance(configuration_item),
                "Annotation":
                    "The user doesn't have MFA enabled.",
                "OrderingTimestamp":
                    configuration_item["configurationItemCaptureTime"]
            },
        ],
        ResultToken=result_token
    )
```

**Comment by KeyboardMonkey** [comment]
I have the same problem.

**Comment by netflash** [comment]
@umerebryx would you mind to create a pull-request ?

**Comment by umerebryx** [comment]
@netflash, created a pull request, please review.

**Comment by netflash** [comment]
@umerebryx I can do the review, however I don't belong to this repo so won't be able to merge it anyway.

**Comment by bhai840** [comment]
Hi guys,
I am pretty new to python lambda. I just wanted to know where are we importing json from? When I run the above code it is giving me the "Key Error". Can you please help me understand it?

Thank you!

**Comment by dilshad18** [comment]
this rule doesn't work yet. please let me know if its been fixed

**Comment by netflash** [comment]
@umerebryx I reckon we might want to reassess this issue, as a user can have MFA devices attached for just cli access. https://docs.aws.amazon.com/cli/latest/reference/iam/enable-mfa-device.html

**Comment by umerebryx** [comment]
@netflash , yeah back then this was not very relevant but you are right now a cli user can have mfa_enabled. So we should probably revert this to the previous state where it checked every user (CLI and Console) for MFA?

**Comment by dilshad18** [comment]
both MFA code are not working.. if possible can you please update ?

**Comment by jongogogo** [comment]
Hi folks, old topic, just to let you know there is a new rule, which works. Have a look: https://github.com/awslabs/aws-config-rules/tree/master/python/IAM_USER_MFA_ENABLED
Feel free to re-open if anything
