### ISSUE TITLE
[Python] iam-* rules not working properly

### ISSUE THREAD

**Issue by markusbecker** [awslabs/aws-config-rules#76]
Hey guys,

im using a lot of the rules you do provide here over quite some time (THANKS!!). But i have issues with some of the rules since they only work when I invoke them on demand.

iam-inactive-user.py
iam-unused-keys.py
iam-unused-user.py
....(and so on)

These AWS Config rules are triggered on resource change, but...

- Users do not change but the passwords/access keys do age out (Config marks them as compliant)
- Keys can be used used and iam users are still marked as unused (Config marks them as non-compliant)
- Users can get inactive but the user does not change (Config marks them as compliant)
- ...

Do you have the same problems? I could maybe change the trigger model to periodic but then i would need to rewrite the whole code since there would be no configurationitem in the invokingevent. 

Any thoughts on this? Thanks guys!

best,
Markus

**Comment by markusbecker** [comment]
Shouldnt the iam config rules be more like [this](https://github.com/awslabs/aws-config-rules/blob/master/python/ec2_require_ebs_snapshots_for_volumes)?

**Comment by mooninite** [comment]
I've added support to the inactive snippet to work for the Periodic type of trigger. Check out pull request 92 to see the code.

**Comment by jongogogo** [comment]
merged #92
