### ISSUE TITLE
Receiving below mentioned error while running the code

### ISSUE THREAD

**Issue by jaganmohan999** [awslabs/aws-config-rules#83]
int' object has no attribute '__getitem__': TypeError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 40, in lambda_handler
    invoking_event = json.loads(event["invokingEvent"])
TypeError: 'int' object has no attribute '__getitem__'

**Comment by jongogogo** [comment]
Which rule is it?

**Comment by jongogogo** [comment]
Closing, no update.
