### ISSUE TITLE
iam_access_key_root_disabled-periodic

### ISSUE THREAD

**Issue by mbharti1** [awslabs/aws-config-rules#85]
Getting result as no results available in the AWS config console.
I have created a Lambda function with the same code present here.
Can you please help.

**Comment by jongogogo** [comment]
Several possibilities:
- There is a problem of IAM permission (lambda), check the CloudWatch logs of the lambda.
- There is a bug in the rule code, check the CloudWatch logs of the lambda.

Please consider those possiblities. Feel free to reopen an issue with the logs if needed or do a PR.
