### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by jtwcarboy** [awslabs/aws-config-rules#88]
Im testing multiple of these,  the MFA test ill use as example.
I get no results available.
Im probably doing something simply wrong but any pointers on why i would get no results?

**Comment by jongogogo** [comment]
Several possibilities:
- You have no resource which is in sope of the rule. For MFA, if you have no users.
- There is a problem of IAM permission (lambda), check the CloudWatch logs of the lambda.
- There is a bug in the rule code, check the CloudWatch logs of the lambda.
